checks:
    php: true

tools:
    external_code_coverage:
        timeout: 1200
        runs: 4

filter:
    excluded_paths:
        - 'app/*'
        - 'bin/*'
        - 'src/AppBundle/DataFixtures/*'
        - 'tests/*'
        - 'var/*'
        - 'web/*'
