language: php

php:
    - 7.0
    - 7.1

env:
    - DB=mysql
    - DB=pgsql

install:
    - cp app/config/travis/parameters.$DB.yml app/config/parameters.yml
    - composer --no-interaction install

before_script:
    - ./bin/console --env=test --no-interaction doctrine:database:create
    - ./bin/console --env=test --no-interaction doctrine:schema:create
    - ./bin/console --env=test --no-interaction doctrine:fixtures:load

script:
    - ./vendor/bin/simple-phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
