services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eTraxis\AccountsDomain\Application\CommandHandler\:
        resource: '../../../Application/CommandHandler'

    # Autowiring hints
    eTraxis\AccountsDomain\Application\CommandHandler\LockAccountHandler:
        $authFailures: '%auth_failures%'
        $lockDuration: '%lock_duration%'

    # Autowiring hints
    eTraxis\AccountsDomain\Application\CommandHandler\RegisterExternalAccountHandler:
        $locale: '%locale%'
        $theme:  '%theme%'
