imports:
    - { resource: parameters.yml }
    - { resource: security.yml   }
    - { resource: services.yml   }

framework:
    #esi: ~
    translator: { fallbacks: ['en'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    web_link: true
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        locale: '%locale%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            model:
                type:      annotation
                dir:       '%kernel.project_dir%/src/eTraxis/Entity'
                prefix:    eTraxis\Entity
                alias:     eTraxis
                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport:  '%mailer_transport%'
    host:       '%mailer_host%'
    port:       '%mailer_port%'
    encryption: '%mailer_encryption%'
    username:   '%mailer_user%'
    password:   '%mailer_password%'
    spool:      { type: memory }
