pignus_login:
    resource: '@PignusBundle/Resources/routing/login.yml'

user:
    resource: '@AppBundle/Controller/User/'
    type:     annotation
    prefix:   /

admin:
    resource: '@AppBundle/Controller/Admin/'
    type:     annotation
    prefix:   /admin
