PignusLogin:
    resource: '@PignusBundle/Resources/routing/login.yml'

AccountsDomain:
    resource: '../src/AccountsDomain/Framework/Resources/config/routing.yml'

SharedDomain:
    resource: '../src/SharedDomain/Framework/Resources/config/routing.yml'
