security:

    encoders:
        eTraxis\Entity\User: plaintext

    providers:
        etraxis_provider:
            id: etraxis.provider.generic

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous:  ~
            form_login: ~
            logout:     ~

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,      roles: ROLE_USER                    }
