security:

    encoders:
        eTraxis\AccountsDomain\Domain\Model\User: bcrypt
        legacy.md5:
            id: eTraxis\AccountsDomain\Framework\Authentication\Md5PasswordEncoder
        legacy.sha1:
            id: eTraxis\AccountsDomain\Framework\Authentication\Sha1PasswordEncoder

    providers:
        etraxis_provider:
            id: etraxis.provider.generic

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout:    ~
            guard:
                entry_point: etraxis.authenticator.generic
                authenticators:
                    - etraxis.authenticator.ldap
                    - etraxis.authenticator.generic

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN                   }
        - { path: ^/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: ROLE_USER                    }
