services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    eTraxis\SharedDomain\Framework\EventSubscriber\:
        resource: '../../EventSubscriber'

    # Autowiring hints
    eTraxis\SharedDomain\Framework\EventSubscriber\StickyLocale:
        $locale: '%locale%'
