services:

    _defaults:
        autowire: true
        public: true

    eTraxis\Application\Handler\:
        resource: '../../../src/Application/Handler'

    # Alias for autowiring
    League\Tactician\CommandBus: '@tactician.commandbus'

    # Custom middleware
    tactician.middleware.timing:
        class: eTraxis\Framework\CommandBus\TimingMiddleware
        public: false

    # Custom handler locator
    eTraxis\Framework\CommandBus\HandlerLocator:
        public: false
        calls: [[ setContainer, [ '@service_container' ] ]]

    # Overridden command handler middleware to inject custom handler locator
    tactician.middleware.command_handler:
        class: League\Tactician\Handler\CommandHandlerMiddleware
        public: false
        arguments:
            - '@tactician.handler.command_name_extractor.class_name'
            - '@eTraxis\Framework\CommandBus\HandlerLocator'
            - '@tactician.handler.method_name_inflector.handle'

    # Autowiring hints
    eTraxis\Application\Handler\User\LockAccountHandler:
        $authFailures: '%auth_failures%'
        $lockDuration: '%lock_duration%'

    # Autowiring hints
    eTraxis\Application\Handler\User\RegisterExternalAccountHandler:
        $locale: '%locale%'
        $theme:  '%theme%'
