services:

    _defaults:
        autowire: true
        public: true

    # Alias for autowiring
    League\Tactician\CommandBus: '@tactician.commandbus'

    # Custom middleware
    tactician.middleware.timing:
        class: eTraxis\CommandBus\TimingMiddleware
        public: false
