services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    eTraxis\EventSubscriber\:
        resource: '../../../src/eTraxis/EventSubscriber'

    # Autowiring hints
    eTraxis\EventSubscriber\StickyLocale:
        $locale: '%locale%'
