services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    eTraxis\Framework\EventSubscriber\:
        resource: '../../../src/Framework/EventSubscriber'

    # Autowiring hints
    eTraxis\Framework\EventSubscriber\StickyLocale:
        $locale: '%locale%'
